
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: {{ toJson .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}