apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  database: {{ .Values.postgres.database | b64enc | quote }}
