version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8080:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb
    depends_on:
      db: 
        condition: service_healthy
  
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "8001:8001"
    environment:
      - FLASK_APP=client.py
      - FLASK_ENV=development

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
