apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: "{{ if .Values.image.repository }}{{ .Values.image.repository }}{{ else }}message-service{{ end }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
