apiVersion: v1
kind: Service
metadata:
  name: message-service
  labels:
    app: message-service
spec:
  type: ClusterIP
  selector:
    app: message-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http