apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker-redis
  labels:
    app: message-broker-redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: message-broker-redis
  template:
    metadata:
      labels:
        app: message-broker-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          resources: {{- toYaml .Values.resources | nindent 12 }}
